name: Auto Release with GH CLI

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      - name: Determine Next Tag
        id: tag
        run: |
          prefix="release"
          latest_commit=$(git rev-parse --short HEAD)
          echo "tag=${prefix}-${latest_commit}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release via gh
        env:
          GH_TOKEN: ${{ secrets.FG_PAT }}
        run: |
          tag="${{ steps.tag.outputs.tag }}"
          gh release create "$tag" --title "$tag" --notes "Automated release"
