name: Auto Release

on:
  push:
    branches: [main]

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: |
          prefix="release-" # or "testing-" if desired
          latest=$(git tag | grep "^$prefix" | sort -V | tail -n1)
          num=${latest#$prefix}
          next=$((num + 1))
          echo "tag=${prefix}${next}" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "${{ steps.get_tag.outputs.tag }}" -m "Auto release"
          git push origin "${{ steps.get_tag.outputs.tag }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
