name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git and Authentication
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # Set remote URL to use the FG-PAT for authentication
          git remote set-url origin https://x-access-token:${{ secrets.FG_PAT }}@github.com/${{ github.repository }}

      - name: Determine Next Release Tag
        id: get_tag
        run: |
          prefix="release-"
          latest=$(git tag | grep "^$prefix" | sort -V | tail -n1)
          num=${latest#$prefix}
          num=${num:-0}
          next=$((num + 1))
          echo "tag=${prefix}${next}" >> $GITHUB_OUTPUT

      - name: Create and Push Tag
        run: |
          git tag -a "${{ steps.get_tag.outputs.tag }}" -m "Auto release"
          git push origin "${{ steps.get_tag.outputs.tag }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.FG_PAT }}
