name: Auto Release with GH CLI

on:
  push:
    tags:   []
    branches: '**'
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      - name: Determine Tag Info
        id: tag
        run: |
          branch="${GITHUB_REF#refs/heads/}"
          commit=$(git rev-parse --short HEAD)
          tag="${branch}-${commit}"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          if [[ "$branch" != "main" ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.FG_PAT }}
        run: |
          tag="${{ steps.tag.outputs.tag }}"
          prerelease="${{ steps.tag.outputs.prerelease }}"
          gh release create "$tag" \
            --title "$tag" \
            --notes "Automated release from $tag" \
            $( [[ "$prerelease" == "true" ]] && echo "--prerelease" )
