name: Auto Release with GH CLI

on:
  push:
    branches: [main, testing]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      - name: Fetch Branch Info
        id: branch
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Fetch Tag Info
        id: tag
        run: |
          prefix="${{ steps.branch.outputs.branch }}"
          latest_commit=$(git rev-parse --short HEAD)
          echo "tag=${prefix}-${latest_commit}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release via gh
        env:
          GH_TOKEN: ${{ secrets.FG_PAT }}
        run: |
          tag="${{ steps.tag.outputs.tag }}"
          branch="${{ steps.branch.outputs.branch }}"
          extra=""
          if [[ "$branch" != "main" ]]; then
            extra="--prerelease"
          fi
          gh release create "$tag" $extra \
            --title "$tag" \
            --notes "Automated release from $branch" \
            src/minedev.ps1
