name: Auto Release with GH CLI

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      - name: Determine Next Tag
        id: tag
        run: |
          prefix="release-"
          latest=$(git tag | grep "^$prefix" | sort -V | tail -n1)
          num=${latest#$prefix}
          num=${num:-0}
          next=$((num + 1))
          echo "tag=${prefix}${next}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release via gh
        env:
          GH_TOKEN: ${{ secrets.FG_PAT }}
        run: |
          tag="${{ steps.tag.outputs.tag }}"
          gh release create "$tag" --title "$tag" --notes "Automated release"
